#!/usr/bin/env python3
"""Patches the Android project generated by `flutter create`."""

import re
import sys
from pathlib import Path

MANIFEST_PATH = Path("android/app/src/main/AndroidManifest.xml")
APP_BUILD_GRADLE = Path("android/app/build.gradle")
APP_BUILD_GRADLE_KTS = Path("android/app/build.gradle.kts")
PROVIDER_PATHS = Path("android/app/src/main/res/xml/provider_paths.xml")

REQUIRED_PERMISSIONS = [
    '<uses-permission android:name="android.permission.INTERNET"/>',
    '<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>',
    '<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="32"/>',
    '<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32"/>',
    '<uses-permission android:name="android.permission.READ_MEDIA_AUDIO"/>',
    '<uses-permission android:name="android.permission.READ_MEDIA_VIDEO"/>',
    '<uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>',
    '<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES"/>',
    '<uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>',
    '<uses-permission android:name="android.permission.FOREGROUND_SERVICE_DATA_SYNC"/>',
    '<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>',
    '<uses-permission android:name="android.permission.WAKE_LOCK"/>',
    '<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>',
    '<uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"/>',
]

DOWNLOADER_PROVIDER = '''
        <!-- flutter_downloader: open file from notification -->
        <provider
            android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
            android:authorities="${applicationId}.flutter_downloader.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>

        <!-- Keep downloads alive in background / after leaving the app -->
        <service
            android:name="androidx.work.impl.foreground.SystemForegroundService"
            android:foregroundServiceType="dataSync"
            android:exported="false"
            tools:node="merge"/>

        <meta-data
            android:name="vn.hunghd.flutterdownloader.NOTIFICATION_ICON"
            android:resource="@mipmap/ic_launcher"/>

        <receiver
            android:name="androidx.work.impl.background.systemalarm.RescheduleReceiver"
            android:exported="false"
            tools:node="merge">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
            </intent-filter>
        </receiver>
'''

PROVIDER_PATHS_XML = '''<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path name="external_files" path="."/>
    <files-path name="files" path="."/>
    <cache-path name="cache" path="."/>
    <external-files-path name="external_files_path" path="."/>
    <external-cache-path name="external_cache" path="."/>
    <root-path name="root" path="."/>
</paths>
'''

APP_LABEL = "INK"
COMPILE_SDK = 35
TARGET_SDK = 35
MIN_SDK = 24


def ensure_provider_paths() -> None:
    PROVIDER_PATHS.parent.mkdir(parents=True, exist_ok=True)
    if not PROVIDER_PATHS.exists():
        PROVIDER_PATHS.write_text(PROVIDER_PATHS_XML, encoding="utf-8")
        print(f"Created {PROVIDER_PATHS}")
    else:
        print(f"Already exists: {PROVIDER_PATHS}")


def patch_manifest() -> None:
    if not MANIFEST_PATH.exists():
        sys.exit(f"ERROR: {MANIFEST_PATH} not found. Run flutter create first.")

    text = MANIFEST_PATH.read_text(encoding="utf-8")

    if 'xmlns:tools=' not in text:
        text = text.replace(
            '<manifest',
            '<manifest xmlns:tools="http://schemas.android.com/tools"',
            1,
        )

    manifest_open = re.search(r"<manifest[^>]*>", text)
    if manifest_open:
        insert_at = manifest_open.end()
        missing = []
        for p in REQUIRED_PERMISSIONS:
            perm_name = re.search(r'android:name="([^"]+)"', p)
            if perm_name and perm_name.group(1) not in text:
                missing.append(p)
        if missing:
            block = "\n    " + "\n    ".join(missing)
            text = text[:insert_at] + block + text[insert_at:]

    if 'android:label="' in text:
        text = re.sub(
            r'android:label="[^"]*"',
            f'android:label="{APP_LABEL}"',
            text,
            count=1,
        )

    if "android:usesCleartextTraffic" not in text:
        text = re.sub(
            r"(<application\b)",
            r'\1\n        android:usesCleartextTraffic="false"',
            text,
            count=1,
        )

    if "requestLegacyExternalStorage" not in text:
        text = re.sub(
            r"(<application\b)",
            r'\1\n        android:requestLegacyExternalStorage="true"',
            text,
            count=1,
        )

    if "flutter_downloader.provider" not in text:
        text = re.sub(
            r"(</application>)",
            DOWNLOADER_PROVIDER + r"\1",
            text,
            count=1,
        )

    MANIFEST_PATH.write_text(text, encoding="utf-8")
    print(f"Patched {MANIFEST_PATH}")


def patch_build_gradle() -> None:
    path = APP_BUILD_GRADLE if APP_BUILD_GRADLE.exists() else APP_BUILD_GRADLE_KTS
    if not path.exists():
        print("WARNING: build.gradle not found")
        return

    text = path.read_text(encoding="utf-8")
    print(f"--- {path} before ---")
    print(text[:900])
    print("---")

    text = re.sub(
        r"compileSdk\s*=\s*flutter\.compileSdkVersion",
        f"compileSdk = {COMPILE_SDK}",
        text,
    )
    text = re.sub(
        r"targetSdk\s*=\s*flutter\.targetSdkVersion",
        f"targetSdk = {TARGET_SDK}",
        text,
    )
    text = re.sub(
        r"minSdk\s*=\s*flutter\.minSdkVersion",
        f"minSdk = {MIN_SDK}",
        text,
    )

    text = re.sub(r"compileSdk\s*=?\s*\d+", f"compileSdk = {COMPILE_SDK}", text)
    text = re.sub(
        r"compileSdkVersion\s+\d+", f"compileSdkVersion {COMPILE_SDK}", text
    )
    text = re.sub(r"targetSdk\s*=?\s*\d+", f"targetSdk = {TARGET_SDK}", text)
    text = re.sub(
        r"targetSdkVersion\s+\d+", f"targetSdkVersion {TARGET_SDK}", text
    )
    text = re.sub(r"minSdk\s*=?\s*\d+", f"minSdk = {MIN_SDK}", text)
    text = re.sub(r"minSdkVersion\s+\d+", f"minSdkVersion {MIN_SDK}", text)

    text = re.sub(
        r"compileSdk\s*=\s*flutter\.[A-Za-z0-9_]+",
        f"compileSdk = {COMPILE_SDK}",
        text,
    )
    text = re.sub(
        r"targetSdk\s*=\s*flutter\.[A-Za-z0-9_]+",
        f"targetSdk = {TARGET_SDK}",
        text,
    )

    if not re.search(r"compileSdk\s*=\s*\d+", text):
        text = re.sub(
            r"(android\s*\{)",
            rf"\1\n    compileSdk = {COMPILE_SDK}",
            text,
            count=1,
        )

    path.write_text(text, encoding="utf-8")
    print(f"Patched {path}")
    print(f"--- {path} after ---")
    print(path.read_text(encoding="utf-8")[:900])
    print("---")


def main() -> None:
    ensure_provider_paths()
    patch_manifest()
    patch_build_gradle()


if __name__ == "__main__":
    main()
